# -*- coding: utf-8 -*-
"""Homework 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bMUuxSEduhZRyw0muFDeYX1cpKvTw9Fi

# Homework 1
## Matthew Noel

9.16

a) Downloaded from kaggle

b)
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('diamonds.csv', index_col=0)

"""c)"""

df.head(7)

"""d)"""

df.tail(7)

"""e)"""

df.describe()

"""f)"""

df['cut'].squeeze().describe()

df['color'].squeeze().describe()

df['clarity'].squeeze().describe()

"""g)"""

df['cut'].squeeze().unique()

df['color'].squeeze().unique()

df['clarity'].squeeze().unique()

"""h)"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
histogram = df.hist()